[package]
name = "intro"
version = "0.1.0"
edition = "2021"
authors = [
    "Rock Lo <roxhustlin@gmail.com>",
]
description = "Learning Rust Fast"

[workspace]
members = ["crates/*"]

[dependencies]
clap = { version = "3.2.8", features = ["derive"] }
toolkit = { path = "crates/toolkit" }
